from __future__ import annotations

from dataclasses import replace
from typing import Any

from resonance_field.phase16_config import PhaseXVIConfig


CURRICULUM_OVERRIDES: dict[str, dict[str, Any]] = {
    "neutral_loading": {},
    "dialectic_literary": {
        "quantized_reference_blend": 0.66,
        "quantized_scalar_memory_weight": 0.26,
        "quantized_scalar_trust_weight": 0.24,
        "quantized_repulsive_scale": 0.52,
        "modulation_focus_fraction": 0.34,
        "modulation_beam_count": 18,
        "modulation_angle_spread": 1.95,
        "modulation_score_threshold": -0.04,
        "phase_manipulation_phase_blend": 0.70,
        "phase_manipulation_freq_blend": 0.32,
        "phase_manipulation_trust_margin": 0.08,
        "phase_manipulation_align_threshold": 0.20,
    },
    "mathematics_philosophy": {
        "quantized_reference_blend": 0.70,
        "quantized_scalar_phase_weight": 0.22,
        "quantized_scalar_freq_weight": 0.24,
        "quantized_scalar_trust_weight": 0.30,
        "quantized_scalar_memory_weight": 0.24,
        "quantized_lock_width_bins": 14.0,
        "quantized_drive_scale": 0.56,
        "modulation_focus_fraction": 0.28,
        "modulation_beam_count": 16,
        "modulation_angle_spread": 1.55,
        "modulation_freq_blend": 0.28,
        "phase_manipulation_phase_blend": 0.62,
        "phase_manipulation_freq_blend": 0.40,
        "phase_manipulation_freq_threshold": 0.040,
        "phase_manipulation_memory_ceiling": 0.62,
    },
    "psychological_extrapolation": {
        "quantized_reference_blend": 0.60,
        "quantized_scalar_memory_weight": 0.30,
        "quantized_scalar_trust_weight": 0.28,
        "quantized_scalar_phase_weight": 0.24,
        "quantized_scalar_freq_weight": 0.18,
        "quantized_shell_trust_min": 0.20,
        "quantized_shell_trust_max": 0.90,
        "modulation_focus_fraction": 0.42,
        "modulation_beam_count": 20,
        "modulation_angle_spread": 2.25,
        "modulation_memory_boost": 0.82,
        "modulation_score_threshold": -0.08,
        "phase_manipulation_trust_margin": 0.14,
        "phase_manipulation_align_threshold": 0.22,
        "phase_manipulation_recovery_phase_tol": 0.30,
    },
    "biological_synthesizer": {
        "quantized_reference_blend": 0.72,
        "quantized_scalar_phase_weight": 0.18,
        "quantized_scalar_freq_weight": 0.20,
        "quantized_scalar_trust_weight": 0.26,
        "quantized_scalar_memory_weight": 0.36,
        "quantized_lock_width_bins": 18.0,
        "quantized_drive_scale": 0.52,
        "quantized_vector_freq_gain": 0.036,
        "modulation_focus_fraction": 0.32,
        "modulation_beam_count": 24,
        "modulation_angle_spread": 1.85,
        "modulation_freq_blend": 0.34,
        "modulation_memory_boost": 0.94,
        "modulation_ki_base": 0.34,
        "modulation_ki_gain": 1.02,
        "phase_manipulation_phase_blend": 0.58,
        "phase_manipulation_freq_blend": 0.44,
        "phase_manipulation_memory_ceiling": 0.56,
        "phase_manipulation_freq_threshold": 0.036,
    },
    "ontology_void_finitude": {
        "quantized_reference_blend": 0.74,
        "quantized_anchor_scalar": 0.50,
        "quantized_scalar_phase_weight": 0.16,
        "quantized_scalar_freq_weight": 0.18,
        "quantized_scalar_trust_weight": 0.24,
        "quantized_scalar_memory_weight": 0.42,
        "quantized_lock_width_bins": 20.0,
        "quantized_drive_scale": 0.50,
        "quantized_repulsive_scale": 0.48,
        "quantized_vector_phase_gain": 0.040,
        "quantized_vector_freq_gain": 0.030,
        "quantized_vector_geometry_gain": 0.016,
        "modulation_focus_fraction": 0.26,
        "modulation_beam_count": 14,
        "modulation_angle_spread": 1.30,
        "modulation_spatial_sigma": 0.96,
        "modulation_phase_strength": 0.26,
        "modulation_freq_blend": 0.22,
        "modulation_geometry_pull": 0.72,
        "modulation_memory_boost": 0.98,
        "modulation_score_threshold": -0.02,
        "modulation_ki_base": 0.30,
        "modulation_ki_gain": 0.92,
        "phase_manipulation_phase_blend": 0.52,
        "phase_manipulation_freq_blend": 0.30,
        "phase_manipulation_trust_margin": 0.06,
        "phase_manipulation_align_threshold": 0.16,
        "phase_manipulation_memory_ceiling": 0.48,
        "phase_manipulation_freq_threshold": 0.032,
        "phase_manipulation_recovery_phase_tol": 0.22,
    },
}


def apply_curriculum(config: PhaseXVIConfig, curriculum: str) -> PhaseXVIConfig:
    overrides = CURRICULUM_OVERRIDES.get(curriculum, {})
    if not overrides:
        return config
    return replace(config, **overrides)
